name: stroll_bonfire
description: "Ui mockup of the stroll app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Proxima Nova
      fonts:
          - asset: assets/fonts/ProximaNova-Bold.otf
          - asset: assets/fonts/ProximaNova-Black.otf
          - asset: assets/fonts/ProximaNova-BlackItalic.otf
          - asset: assets/fonts/ProximaNova-BoldItalic.otf
          - asset: assets/fonts/ProximaNova-Extrabold.otf
          - asset: assets/fonts/ProximaNova-ExtraboldItalic.otf
          - asset: assets/fonts/ProximaNova-Italic.otf
          - asset: assets/fonts/ProximaNova-Light.otf
          - asset: assets/fonts/ProximaNova-LightItalic.otf
          - asset: assets/fonts/ProximaNova-Regular.otf
          - asset: assets/fonts/ProximaNova-Semibold.otf
          - asset: assets/fonts/ProximaNova-SemiboldItalic.otf
